"""pes utulek

Revision ID: 626834f13743
Revises: 706c7b82c0f1
Create Date: 2024-01-07 19:40:45.797632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626834f13743'
down_revision = '706c7b82c0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utulek_adresa', sa.String(length=45), nullable=False))
        batch_op.create_foreign_key(None, 'utulek', ['utulek_adresa'], ['adresa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('utulek_adresa')

    # ### end Alembic commands ###
