"""Zakladni

Revision ID: 830771736719
Revises: 
Create Date: 2023-12-23 18:09:48.476821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830771736719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.alter_column('fotografie',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_foreign_key(None, 'utulek', ['utulek_nazev'], ['nazev'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fotografie',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               nullable=True)

    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
