"""empty message

Revision ID: 94a2a6bb20bc
Revises: 830771736719
Create Date: 2023-12-23 18:24:24.549729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a2a6bb20bc'
down_revision = '830771736719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.alter_column('fotografie',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_foreign_key('utulek_nazev', 'utulek', ['utulek_nazev'], ['nazev'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.drop_constraint('utulek_nazev', type_='foreignkey')
        batch_op.alter_column('fotografie',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
