"""pes model utulek update

Revision ID: a392838f0d97
Revises: 6e01221ce0aa
Create Date: 2024-01-06 18:58:38.191552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a392838f0d97'
down_revision = '6e01221ce0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.alter_column('utulek_nazev',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pes', schema=None) as batch_op:
        batch_op.alter_column('utulek_nazev',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###
